version: "3"

services:
  web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    image: php:7.1.33-fpm
    volumes:
      - ./src:/var/www/html